# Oct.14th
# create 3 docker - Database(Postgre), Database Admin(SQL-based: PGAdmin), Application(Django)

FROM dpage/pgadmin4
ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=pass
EXPOSE 80 

